import java.io.IOException;

import org.web3j.protocol.Web3j;
import org.web3j.protocol.core.methods.response.Web3ClientVersion;
import org.web3j.protocol.http.HttpService;

/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'mboleg' at '15/01/18 13:22' with Gradle 2.14.1
 *
 * @author mboleg, @date 15/01/18 13:22
 */
public class AccessContract {

	public AccessContract(){
	}

	public static void main (String[] args)  { 
		org.slf4j.Logger logger = org.slf4j.LoggerFactory.getLogger(AccessContract.class);
		Web3j web3 = Web3j.build(new HttpService());  // defaults to http://localhost:8545/
		Web3ClientVersion web3ClientVersion;
		try {
			web3ClientVersion = web3.web3ClientVersion().send();
			String clientVersion = web3ClientVersion.getWeb3ClientVersion();
			System.out.println("Client version = " + clientVersion);
		} catch (IOException e) {
			logger.error(e.getMessage());
		}

	}
}
