import org.junit.Test;
import static org.junit.Assert.*;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'mboleg' at '16/01/18 10:34' with Gradle 2.14.1
 *
 * @author mboleg, @date 16/01/18 10:34
 */
public class AccessContractTest {
    @Test public void testSomeLibraryMethod() {
    	AccessContract classUnderTest = new AccessContract();
    }
}
